name: chatbot 
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - icu=68.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libuv=1.40.0
  - ncurses=6.4
  - nodejs=16.13.1
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.11.3
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anyio==3.7.0
      - async-timeout==4.0.2
      - attrs==23.1.0
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - fastapi==0.96.0
      - frozenlist==1.3.3
      - h11==0.14.0
      - httptools==0.5.0
      - idna==3.4
      - multidict==6.0.4
      - openai==0.27.7
      - pydantic==1.10.8
      - python-dotenv==1.0.0
      - pyyaml==6.0
      - regex==2023.6.3
      - requests==2.31.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - tiktoken==0.4.0
      - tqdm==4.65.0
      - typing-extensions==4.6.3
      - urllib3==2.0.2
      - uvicorn==0.22.0
      - uvloop==0.17.0
      - watchfiles==0.19.0
      - websockets==11.0.3
      - yarl==1.9.2
